### ISSUE TITLE
Validator is not online

### ISSUE THREAD

**Issue by paschty** [IIIF/image-api#37]
The Validator is not online. You can see the Formular you get 404 if you send it.

http://iiif.io/api/image/validator/

**Comment by azaroth42** [comment]
Working now, might have been a temporary network outage?

**Comment by acdha** [comment]
Hmmm, yes – I get a 404 on the results page as well:

http://iiif.io/api/image/validator/results.html?server=https%3A%2F%2Fcontent.wdl.org&prefix=iiif&identifier=iiif-validator-test-image&version=2.0&level=1&id_squares=on&info_json=on&id_basic=on&id_error_escapedslash=on&id_error_unescaped=on&id_escaped=on&id_error_random=on&region_error_random=on&region_pixels=on&size_region=on&size_error_random=on&size_ch=on&size_wc=on&size_percent=on&rot_error_random=on&quality_error_random=on&format_jpg=on&format_error_random=on&jsonld=on&baseurl_redirect=on&cors=on

**Comment by azaroth42** [comment]
Fixed. Thanks both!
